// One-shot script: convert the ANSI Shadow figlet "ccws" logo into SVG
// <path> elements using SF Mono glyph outlines. Replaces the <text>-based
// logo in assets/screenshots/picker.svg, which depended on the host font
// and rendered with broken column alignment.
//
// Run: bun run scripts/gen-logo-paths.ts
import { readFileSync } from 'node:fs';
import opentype from 'opentype.js';

const FONT_PATH = '/System/Library/Fonts/SFNSMono.ttf';
const buf = readFileSync(FONT_PATH);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

const LOGO_LINES = [
  ' ██████╗ ██████╗██╗    ██╗███████╗',
  '██╔════╝██╔════╝██║    ██║██╔════╝',
  '██║     ██║     ██║ █╗ ██║███████╗',
  '██║     ██║     ██║███╗██║╚════██║',
  '╚██████╗╚██████╗╚███╔███╔╝███████║',
  ' ╚═════╝ ╚═════╝ ╚══╝╚══╝ ╚══════╝',
];
const COLORS = ['mv', 'pk', 'lv', 'sk', 'gn', 'yl'];

const fontSize = 18;
const lineHeight = 18;
const xOffset = 16;
const yBase = 15;

console.log(`<!-- logo paths generated by scripts/gen-logo-paths.ts from SF Mono -->`);
for (let i = 0; i < LOGO_LINES.length; i++) {
  const y = yBase + i * lineHeight;
  const path = font.getPath(LOGO_LINES[i], xOffset, y, fontSize);
  const d = path.toPathData(2);
  console.log(`<path class="${COLORS[i]}" d="${d}"/>`);
}
